services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
    container_name: docker-node-tut
    restart: always
    ports:
      - "3000:3000"
    healthcheck:
      test: curl --fail "http://localhost:3000/" || exit 1
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s