services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
    container_name: docker-node-tut
    restart: always
    ports:
      - "3000:3000"
    command: bash -c usr/src/app/start.sh
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s